version: 0.1

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    commands:
      - echo installing maven...
      - apt-get update -y
      - apt-get install -y maven
  build:
    commands:
      - echo building the demo-github-ec2-codedeploy
      - mvn install
artifacts:
  files:
    - target/*.jar
    - src/main/resources/scripts/*.sh
    - appspec.yml
    - src/main/resources/application.yml
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'