# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  deploy:
    name: CD Pipeline
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ['8.x']
        appname: ['demogithubactions']
        deploy-group: ['prod']
        s3-bucket: ['sigo-codedeploy-deployments']
        s3-filename: ['prod-aws-codedeploy-${{ github.sha }}']

    # Install AWS CLI 2
    - name: Install AWS CLI 2
      run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" unzip awscliv2.zip sudo ./aws/install

    # Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       aws-region: ap-southeast-1

    # Deploy push to AWS S3
    - name: AWS Deploy push
      run: |
       aws deploy push \
       --application-name ${{ matrix.appname }} \
       --description "This is a revision for the ${{ matrix.appname }}-${{ github.sha }}" \
       --ignore-hidden-files \
       --s3-location s3://${{ matrix.s3-bucket }}/${{ matrix.s3-filename }}.zip \
       --source .


    # Create deployment to CodeDeploy
    - name: AWS Create Deployment
      run: |
       aws deploy create-deployment \
       --application-name ${{ matrix.appname }} \
       --deployment-config-name CodeDeployDefault.OneAtATime \
       --deployment-group-name ${{ matrix.deploy-group }} \
       --file-exists-behavior OVERWRITE \
       --s3-location bucket=${{ matrix.s3-bucket }},key=${{ matrix.s3-filename }}.zip,bundleType=zip \